site_name: envas（エンバス） ヘルプサイト
site_description: WEB 席次表 envas（エンバス） ヘルプサイトです。
site_author: envas
site_url: https://help.envas.jp/
copyright: "&copy; 2025 WISH LLC. All rights reserved."

theme:
  name: material
  logo: images/envas.png
  favicon: images/favicon.ico
  language: ja
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.top

extra_css:
  - stylesheets/extra.css

plugins:
  search:
    lang: "ja"

extra:
  generator: false

markdown_extensions:
  - nl2br
  - admonition
  - attr_list

nav:
  - はじめに: index.md
  - ゲストの管理: guest.md
  - 席次表の使い方: seating-chart.md
  - フォトギャラリー: photo-gallery.md
  - 二次会の設定: after-party.md
  - よくあるご質問: faq.md
